# Metadata:
#   Creation Date: 2024/11/02 20:13
#   Last Update Date: 2024/11/02 20:13
#   Author: git@xiaobo.tw
name: Python workflows (for DiscordMeetScribe)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Discord Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        set -e
        nohup python run.py > discord_bot.log 2>&1 &
        sleep 10
        if ! pgrep -f "python run.py"; then
          echo "Failed to start Discord Bot."
          cat discord_bot.log
          exit 1
        else
          echo "Discord Bot is running successfully."
        fi

    - name: Show Discord Bot log
      if: failure()
      run: |
        echo "Discord Bot log:"
        cat discord_bot.log
